#This file is the entrypoint for spring to know where to look for the configuration file
#and will hold some configuration needed for

spring:
  application:
    name: REGISTRY_SERVICE #name of the application
  cloud:
    config:
      uri: http://localhost:8888/ #where the config-service is running
      fail-fast: true #the service will not run if it can't reach the config-service
      password: 1234 #password of the config-service
      username: user #username of the config-service
  jmx:
    enabled: false
eureka:
  instance:
    prefer-ip-address: true #when the application registers with eureka, it uses its IP address rather than its hostname
#    hostname: localhost
  client:
    registerWithEureka: false #tells the built-in eureka client to not register itself with eureka, because we should act as a server
    fetchRegistry: false
server:
  port: 8761
logging:
  file:
    name: /tmp/registerserver.log
